# Generated by Django 4.0.4 on 2022-04-30 06:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('plantId', models.CharField(default=api.models.idgen, max_length=20, primary_key=True, serialize=False)),
                ('plantName', models.CharField(default=' ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Soils',
            fields=[
                ('soilId', models.CharField(default=api.models.idgen, max_length=20, primary_key=True, serialize=False)),
                ('soilName', models.CharField(default=' ', max_length=20)),
                ('plants', models.ManyToManyField(to='api.plants')),
            ],
        ),
    ]
