# Generated by Django 4.0.4 on 2022-04-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='Plant',
        ),
        migrations.RenameModel(
            old_name='Soils',
            new_name='Soil',
        ),
    ]
