# Generated by Django 4.0.4 on 2022-05-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_soil_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='diseases',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizers',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='plant',
            name='wateringFrequency',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='wateringLevel',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
